<div class="text">
	<h1 align="center">Shihan</h1><br>
	<h2>MILENKO RAILIĆ 6. DAN</h2><br>
	<h4>
		<ul class="bulen">
			<li>» Izpit za 6. Dan je opravil dne 19.06.2011 v Vrhniki: št. diploma no.: SLO-722-11</li>
			<li>» Diplomiral je na Športni akademiji Beograd, smer Višji trener, dne 16.11.2004 serijska številka diplome: 451.</li>
		</ul>
	</h4><br>
	<p>
	Rojen, 06.02.1960, v vasi Štrpci, občina Prnjavor v Republiki Srpski (BiH), kjer je tudi končal osnovno šolo z imenom OŠ »Padlih borcev« Štrpci. Leta 1977 je šel »s trebuhom za kruhom« v Slovenijo, kjer se je tudi začel ukvarjati s karatejem. Lahko bi rekli, da se je s karatejem začel ukvarjati relativno pozno, natančneje pri sedemnajstih letih tako, da nima nobenih tekmovalnih rezultatov iz mlajših kategorij.<br><br>
	Kot tekmovalec se je začel tekmovati za Karate Shotokan klub Koper, pri takratnemu trenerju Polde Jermanu. Glavni trener mu je neuradno, že kot tekmovalcu, prepuščal vodenje treningov, saj je takrat Milenko veliko obiskoval seminarje, ki so jih v osemdesetih uspešno organizirali brata dr. Ilija in Vladimir Jorga ter Oliver Tomić. Od njih se je naučil kako in na kakšen način popravljati sebe kot tekmovalca. Ker pa ga je zanimala tudi trenerska kariera se je od prej omenjenih mojstrov še naučil kako učiti druge na čim bolj racionalen oziroma strokoven način ter obenem kako počasi graditi svojo pot k trenerski karieri.<br><br>
	Po uspešno opravljenem izpitu za mojstra karateja 2.dan leta 1987 je s skupino zaljubljenih v karate, vendar na njegovo iniciativo, ustanovil Shotokan karate klub Piran. Njegovi tekmovalci so že februarja naslednjega leta na regijskem tekmovanju osvojili 8 medalj v športnih borbah in tako so postali najuspešnejši klub v regiji. Na takratnem republiškem prvenstvu je Milenko osvojil drugo mesto, ki mu je dalo dodaten motiv in potrdilo, da opravlja svoje delo dobro. Takoj naslednje leto (1989) je postal državni prvak v super lahki kategoriji. V obdobju med letom 1987 in 1991 je postal trikratni prvak Slovenije v kategoriji športne borbe -60kg WUKO, prvak v kategoriji -65kg SKIF Slovenije. Poleg tega je osvojil tudi 38 prvih mest na različnih mednarodnih turnirjih v kategorijah -60kg, -65kg in absolutno posamezno. Zelo uspešno je tudi nastopal za ekipo TVD Partizan Ruše, kjer je najprej nastopal v prvi ligi Slovenije. Leta 1988 ta ekipa postane državni prvaki, kjer Milenko ne izgubi niti ene borbe. Po tem z isto ekipo nastopi tudi v drugi zvezni ligi SFRJ, kjer so na koncu sezone delili drugo in tretje mesto z ekipo Dinama iz Pančeva, saj so imeli enako število točk. V omenjeni ligi je izgubil samo en dvoboj. Leta 1989 v Velenju nastopi za reprezentanco Slovenije v absolutni kategoriji proti reprezentanci Italije, kjer reprezentanca osvoji prvo mesto. Milenko je končal svojo borbo z remijem, nastopil pa je prvi.<br><br>
	Ves čas uspešne tekmovalne kariere ne zanemarja delo z najmlajšimi v klubu. Čeprav je zelo mlad klub, njegovi tekmovalci konstantno osvajajo izredno dobre rezultate in se kosajo s starejšimi in predvsem bogatejšimi klubi, ki so takrat kupovali tekmovalce iz drugih republik takratne skupne države.  Mlada ekipa Shotokan klub Piran je na SKIF Slovenije osvojila 4. Mesto. Kar je bil v takšni konkurenci, kjer je veliko starejših klubov ojačenih s tekmovalci iz drugih klubov, izreden uspeh. Še posebej, če imamo v vidu, da je ekipa Karate kluba Piran bila celotna iz Pirana in da je bil najvišji pas 1.kyu.<br><br>
	Teženje k vedno boljšem delu se je zavedal, da je za kvalitetno delo potrebno učenje ne samo karateja, vendar tudi splošnega športnega znanja, tako da je leta 1997 diplomiral v Novem Sadu za Trenerja karateja ter ponovno polaga za trenerja - amaterski kader Ljubljana. Zavedajoč, da se karate šport zelo hitro razvija in da je vedno bolj potrebna uporaba znanosti v karateju, se leta 2000 vpisuje na Višjo trenersko šolo na Športni akademiji v Beogradu (Srbija), kjer 16.11.2004 po uspešno opravljenih izpitih diplomira kot višji karate trener.<br><br>
	Že od samega začetka njegove trenerske kariere ga je vodila težnja, da oblikuje vrhunske tekmovalce in to v članski konkurenci v kateri je tudi najtežje doseči opažene rezultate. Po desetih letih dela s številnimi reprezentanti v mlajših kategorijah prihaja tudi članski reprezentant iz njegovega kluba Gabrijel Franca, ki je bil po vhodu v prvo ekipo reprezentance kar desetletje standardni član reprezentance ekipno in v težki kategoriji. Danes ima več tekmovalcev v mlajših kategorijah, ki so člani reprezentance Slovenije, vendar ponovno ustvari enega zelo uspešnega člana, ki je dostojno nasledil starejšega kolega. To je Mladen Railić 11-kratni prvak Slovenije v različnih kategorijah od pionirjev do članov. Osvojil je tudi tretje mesto na Balkanskem prvenstvu v Herceg Novem v Črni Gori ter deveto mesto na Evropskem prvenstvu na Tenerifih v Španiji. Poleg tega je še absolvent na Fakulteti za šport, smer karate in že samostojno dela kot glavni trener v Karate klubu Koper. Članska ekipa DBV Pirana v športnih borbah osvaja pet krat prvo mesto na državnem prvenstvu Slovenije, kjer je nastopila samo pet krat. Vsakič ko je DBV Piran imel prijavljeno ekipo je ta ekipa zasedla prvo mesto. Pod naštetimi rezultati so našteti samo rezultati članov, mlajši člani kluba vsako leto redno osvajajo medalje s številnih tekmovanj.<br><br>
	Kot trener je delal tudi v Karate zvezi Slovenije. Po klicu predsednika zveze sprejme mesto selektorja in glavnega trenerja Slovenske reprezentance za športne borbe članov in članic. Pod njegovim vodstvom je reprezentanca imela solidne rezultate na mednarodnih tekmovanjih nižjega ranga. Najboljši rezultat je osvojeno drugo mesto v športnih borbah na Zlati ligi v Milanu. Na ekipnem regijskem prvenstvu in na evropskem prvenstvu v posameznih kategorijah ni bilo predvidenih rezultatov, zaradi katerih po letu dni daje odpoved na mestu selektorja ter se aktivneje posveti delu z tekmovalci iz kluba DBV Piran in KK Koper.<br><br>
	Zdaj je član komisije za pasove v Karate zvezi Slovenije in sodnik za športne borbe ter kate A ranga.<br>
	Med drugim je tudi dobitnik plakete za najboljšega športnega delavca v občini Piran za leto 2004 in srebrne plakete KZS za trideset let dela v karateju. Izredno uspešno sodeluje s prof. dr. Vladimirom Jorgo, ki je živa legenda jugoslovanskega karateja, Dušanom Dačićem, Oliverom Tomićem, Predragom Stojadinovim, Slavoljubom Piperom, Veljko Kajtazijem (s katerim se je tudi tekmoval za ekipo TVD Partizan Ruše v drugi ligi SFRJ), Dikanom Milosajevićem, ki vodi karate akademijo v Klagenfurtu (Austrija) in Kung-fu mojstrom Milenkom Kozlico iz Avstrije.<br><br><br>
	Ob tej priložnosti se vsem naštetim zahvaljujem na njihovem doprinosu v gradnji njegove športne kariere.
	</p>
</div>